[changelog]
header = "# Changelog\n"
body = """
{% if version %}\
### {{ version | replace(from="v", to="") }} <small>{{ timestamp | date(format="%B %d, %Y") }}</small>
{% else %}\
### Unreleased
{% endif %}\
{% for commit in commits %}
- {{ commit.message | split(pat=":") | last | trim | upper_first }}\
{% if commit.github.pr_number %} [#{{ commit.github.pr_number }}](https://github.com/bryion/minerva-deploy/pull/{{ commit.github.pr_number }}){% endif %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
skip_tags = "nightly"
ignore_tags = ""
topo_order = false
sort_commits = "newest"
protect_breaking_commits = true
commit_parsers = [
  { message = "^doc", skip = true },
  { message = "^style", skip = true },
  { message = "^test", skip = true },
  { message = "^chore", skip = true },
  { message = "^ci", skip = true },
]

[remote.github]
owner = "bryion"
repo = "minerva-deploy"