services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8082:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev:/dev:ro
    command:
      - '-housekeeping_interval=30s' # sync with prometheus.yml scrape interval
      - '-docker_only=true'
    restart: unless-stopped
    privileged: true
    networks:
      - monitoring

networks:
  monitoring:
    external: true