galaxy_info:
  role_name: tailscale
  namespace: bryion
  author: bryion
  description: Thin wrapper for artis3n.tailscale
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - tailscale
    - networking

dependencies:
  - role: artis3n.tailscale
    vars:
      tailscale_authkey: "{{ tailscale_wrapper_authkey }}"
      tailscale_args: "{{ tailscale_wrapper_args }}"
