services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: homepage
    ports:
      - 127.0.0.1:3002:3000
    volumes:
      - ./config:/app/config # Maps current directory to config
      - ./images:/app/public/images # Maps local images folder to public webroot
      - ./icons:/app/public/icons
#     - /media/drive2:/media/drive2
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: nlab.casa,192.168.1.19:3002,minerva.lab:3002 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    restart: unless-stopped