services:
  glances:
    container_name: glances
    image: nicolargo/glances:4.3.0 # minimal + fastAPI & docker, does not include exporters (latest-full)
    restart: unless-stopped
    pid: host
    network_mode: host # 61208 is glances web server port
    volumes:
      - "/:/rootfs:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf:ro"
    environment:
      - "GLANCES_OPT=-w"
    deploy:
      resources:
        limits:
          memory: 512M
    tmpfs:
      - /tmp
    cap_add:
      - SYS_PTRACE
      - DAC_READ_SEARCH
    read_only: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:61208/api/4/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
