---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Reload ufw
  community.general.ufw:
    state: reloaded
  when: ansible_virtualization_type != 'docker'

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when: ansible_virtualization_type != 'docker'
