---
- name: Converge
  hosts: all
  become: true
  vars:
    minerva_tailscale_authkey: "{{ lookup('env', 'TAILSCALE_TEST_KEY') | default('tskey-auth-test', true) }}"
  roles:
    - role: bryion.tailscale
