services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v8.12.15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:9999:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s