---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
#

title: nLab
fullWidth: true
headerStyle: clean
statusStyle: dot
favicon: /images/logo-N-512.png

cardBlur: sm
theme: dark
color: gray
quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: false
target: _blank
hideVersion: true
language: en

# https://gethomepage.dev/configs/settings/#layout
layout:
    main-apps:
        style: row
        columns: 3
        header: false
    other-apps:
        style: row
        columns: 4
        header: false
    has-widget:
        style: row
        columns: 4
        header: false


#background: 
#    image: /images/background.png
#    opacity: 20
#    brightness: 70

#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey
