services:

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring
    extra_hosts:
      - "node_exporter:host-gateway"

networks:
  monitoring:
    external: true

volumes:
  prometheus-data: