services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true

volumes:
  grafana-storage: {}
