---
- name: Converge
  hosts: all
  become: true
  vars:
    harden_minerva_user: minerva
  pre_tasks:
    - name: Create minerva user
      ansible.builtin.user:
        name: "{{ harden_minerva_user }}"
  roles:
    - role: harden
