---
galaxy_info:
  role_name: compose_sync
  author: bryion
  description: Syncs Docker Compose configs and secrets to the remote host
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  license: MIT
